/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/13oShj3yedd
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Archivo } from 'next/font/google'

archivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { CardContent, Card } from "@/components/ui/card"

export function shoe store() {
  return (
    <div className="flex flex-col min-h-[100dvh]">
      <header className="bg-gray-900 text-white py-4 px-6 flex items-center justify-between">
        <Link className="text-2xl font-bold" href="#">
          Sole Stride
        </Link>
        <nav className="hidden md:flex items-center space-x-6">
          <Link className="hover:underline" href="#">
            Home
          </Link>
          <Link className="hover:underline" href="#">
            Shop
          </Link>
          <Link className="hover:underline" href="#">
            New Arrivals
          </Link>
          <Link className="hover:underline" href="#">
            About
          </Link>
          <Link className="hover:underline" href="#">
            Contact
          </Link>
        </nav>
        <Button className="md:hidden">Menu</Button>
      </header>
      <main className="flex-1">
        <section className="bg-gray-100 py-20">
          <div className="container mx-auto grid grid-cols-1 md:grid-cols-2 gap-8 items-center">
            <div>
              <h1 className="text-4xl font-bold mb-4 animate-slide-in">
                Step into Style with Our Latest Shoe Collection
              </h1>
              <p className="text-gray-600 mb-8">Discover the perfect pair of shoes to elevate your look and comfort.</p>
              <Link
                className="inline-flex items-center space-x-2 bg-gradient-to-r from-[#333] to-[#999] text-white px-6 py-3 rounded-md hover:bg-gradient-to-r hover:from-[#666] hover:to-[#ccc] focus:outline-none focus:ring-2 focus:ring-[#333] focus:ring-offset-2 focus:ring-offset-gray-900 shadow-lg shadow-[#333]/50 animate-pulse"
                href="#"
              >
                <span>Shop Now</span>
                <ArrowRightIcon className="h-5 w-5" />
              </Link>
            </div>
            <div>
              <img
                alt="Featured Shoe"
                className="w-full h-auto rounded-lg shadow-lg"
                height={500}
                src="shoes-3592530_640.jpg"
                style={{
                  aspectRatio: "500/500",
                  objectFit: "cover",
                }}
                width={500}
              />
            </div>
          </div>
        </section>
        <section className="py-16">
          <div className="container mx-auto">
            <h2 className="text-3xl font-bold mb-8">Shop by Category</h2>
            <div className="grid grid-cols-2 md:grid-cols-4 gap-6">
              <Link className="bg-white rounded-lg shadow-md overflow-hidden group" href="#">
                <img
                  alt="Sneakers"
                  className="w-full h-48 object-cover group-hover:scale-105 transition-transform duration-300"
                  height={200}
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "300/200",
                    objectFit: "cover",
                  }}
                  width={300}
                />
                <div className="p-4">
                  <h3 className="text-lg font-bold mb-2">Sneakers</h3>
                  <p className="text-gray-600">Casual and athletic styles</p>
                </div>
              </Link>
              <Link className="bg-white rounded-lg shadow-md overflow-hidden group" href="#">
                <img
                  alt="Heels"
                  className="w-full h-48 object-cover group-hover:scale-105 transition-transform duration-300"
                  height={200}
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "300/200",
                    objectFit: "cover",
                  }}
                  width={300}
                />
                <div className="p-4">
                  <h3 className="text-lg font-bold mb-2">Heels</h3>
                  <p className="text-gray-600">Elegant and stylish options</p>
                </div>
              </Link>
              <Link className="bg-white rounded-lg shadow-md overflow-hidden group" href="#">
                <img
                  alt="Boots"
                  className="w-full h-48 object-cover group-hover:scale-105 transition-transform duration-300"
                  height={200}
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "300/200",
                    objectFit: "cover",
                  }}
                  width={300}
                />
                <div className="p-4">
                  <h3 className="text-lg font-bold mb-2">Boots</h3>
                  <p className="text-gray-600">Rugged and versatile styles</p>
                </div>
              </Link>
              <Link className="bg-white rounded-lg shadow-md overflow-hidden group" href="#">
                <img
                  alt="Flats"
                  className="w-full h-48 object-cover group-hover:scale-105 transition-transform duration-300"
                  height={200}
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "300/200",
                    objectFit: "cover",
                  }}
                  width={300}
                />
                <div className="p-4">
                  <h3 className="text-lg font-bold mb-2">Flats</h3>
                  <p className="text-gray-600">Comfortable and stylish options</p>
                </div>
              </Link>
            </div>
          </div>
        </section>
        <section className="bg-gray-100 py-16">
          <div className="container mx-auto">
            <h2 className="text-3xl font-bold mb-8">New Arrivals</h2>
            <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
              <Card>
                <img
                  alt="Shoe 1"
                  className="w-full h-48 object-cover rounded-t-lg"
                  height={300}
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "300/300",
                    objectFit: "cover",
                  }}
                  width={300}
                />
                <CardContent className="p-4">
                  <h3 className="text-lg font-bold mb-2">Leather Sneakers</h3>
                  <p className="text-gray-600 mb-4">$89.99</p>
                  <Button>Add to Cart</Button>
                </CardContent>
              </Card>
              <Card>
                <img
                  alt="Shoe 2"
                  className="w-full h-48 object-cover rounded-t-lg"
                  height={300}
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "300/300",
                    objectFit: "cover",
                  }}
                  width={300}
                />
                <CardContent className="p-4">
                  <h3 className="text-lg font-bold mb-2">Suede Loafers</h3>
                  <p className="text-gray-600 mb-4">$69.99</p>
                  <Button>Add to Cart</Button>
                </CardContent>
              </Card>
              <Card>
                <img
                  alt="Shoe 3"
                  className="w-full h-48 object-cover rounded-t-lg"
                  height={300}
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "300/300",
                    objectFit: "cover",
                  }}
                  width={300}
                />
                <CardContent className="p-4">
                  <h3 className="text-lg font-bold mb-2">Canvas Slip-Ons</h3>
                  <p className="text-gray-600 mb-4">$49.99</p>
                  <Button>Add to Cart</Button>
                </CardContent>
              </Card>
              <Card>
                <img
                  alt="Shoe 4"
                  className="w-full h-48 object-cover rounded-t-lg"
                  height={300}
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "300/300",
                    objectFit: "cover",
                  }}
                  width={300}
                />
                <CardContent className="p-4">
                  <h3 className="text-lg font-bold mb-2">Leather Boots</h3>
                  <p className="text-gray-600 mb-4">$99.99</p>
                  <Button>Add to Cart</Button>
                </CardContent>
              </Card>
            </div>
          </div>
        </section>
      </main>
      <footer className="bg-gray-900 text-white py-8 px-6">
        <div className="container mx-auto flex flex-col md:flex-row justify-between items-center">
          <div>
            <h3 className="text-lg font-bold mb-2">Sole Stride</h3>
            <p className="text-gray-400">Elevate your style with our premium shoe collection.</p>
          </div>
          <div className="mt-4 md:mt-0">
            <h3 className="text-lg font-bold mb-2">Contact Us</h3>
            <p className="text-gray-400">
              123 Main Street, Anytown USA
              <br />
              info@solestridestore.com
              <br />
              (555) 555-5555
            </p>
          </div>
        </div>
      </footer>
    </div>
  )
}

function ArrowRightIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="m12 5 7 7-7 7" />
    </svg>
  )
}
